# Generated by Django 4.1.2 on 2022-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('opens', models.CharField(max_length=100)),
                ('high', models.CharField(max_length=100)),
                ('low', models.CharField(max_length=100)),
                ('closes', models.CharField(max_length=100)),
                ('datetime', models.CharField(max_length=100)),
            ],
        ),
    ]
